pilotica:
  DEBUG: False
  API_LOGGING: True
  secret_key: RANDOM # If set to RANDOM a new key is generated every session

# Pilotica Component-Packages to use
components:
  - alias: "base64-transport"
    logging: False